name: turbostart-pnpm
description: A simple action to setup node, install pnpm dependencies, and cache for later use.
branding:
  icon: package
  color: red
inputs:
  TURBO_TOKEN:
    description: "Turbo token for authentication"
    required: true
  TURBO_TEAM:
    description: "Turbo team to use"
    required: true
runs:
  using: composite
  env:
    TURBO_TOKEN: ${{ inputs.TURBO_TOKEN }}
    TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.3.0
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"
    - name: Install Dependencies
      shell: bash
      run: pnpm i
